language: objective-c

notifications:
  email:
    recipients:
      - development@berndrabe.de
    on_success: [always]
    on_failure: [change]

xcode_project: Rotation.xcodeproj
xcode_scheme: Rotation
osx_image: xcode7.2
xcode_sdk: iphonesimulator9.2 



